name: CodeCov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-20.04

    steps:
    - name: Install packages
      run: sudo apt install gcc-10 g++-10 libunwind-dev libdwarf-dev libelf-dev lcov

    - uses: actions/checkout@v2

    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeBuildType: Debug
        buildDirectory: ${{ github.workspace }}/build
        cmakeAppendedArgs: -DSWIMPS_ENABLE_COVERAGE=ON
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: run-tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -VV

    - name: run-lcov
      working-directory: ${{ github.workspace }}/build
      run: lcov --directory . --capture --output-file coverage.info

    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        fail_ci_if_error: true
        file: ${{ github.workspace }}/build/coverage.info
